version: '3'
services: 
    node: 
        container_name: node
        restart: always
        build: .
        ports: 
            - '80:8080'
        links: 
            - mongo
    mongo: 
        container_name: mongo
        image: mongo:3
        ports: 
            - 27017:27017
        